### ISSUE TITLE
State of the Project?

### ISSUE THREAD

**Issue by jsmylnycky** [http-party/node-http-proxy#1354]
As a long time user of node-http-proxy, I have some concerns and hopefully with new owners (http-party), they can shed some light on the state of the project and what they see moving forward.

I've been leveraging this project for over 2.5 years in an enterprise environment, and there's some concerns over the lack of maintenance, support for versions of Node not even close to being LTS anymore, and the vast number of issues and Pull Requests not being acknowledged.

I would absolutely love to become a contributor and help "modernize" things if that's on the agenda, but with the severe lack of activity over the past year, I do not want to spend time working on PRs if they're going to be ignored.

Could someone chime in and let the community know what the intentions are for this project?  I ask all of this respectfully, as someone who greatly values the time and effort spent on this project, and hopeful to see it continue to move into the future :)

Thanks!

**Comment by indexzero** [comment]
@jsmylnycky both @jcrugzz and I have not had the cycles to be as active in maintenance as we would like. `require('http-proxy');` was the first `require` statement I could write where I was requiring code I wrote & published on `npm` – that was 10 years ago.

Since then a lot has changed. The project underwent a full rewrite in 2014 and it's due for another one. Would love to see you (and other folks who are interested) help drive that forward.

You are now a member of the organization with `Maintain` access to this repository. If you could:

1. Start landing everything you want to see in the next release on `master` (PRs, etc). 
2. Open a PR adding a `CHANGELOG.md` for the new version with release notes of what PRs were merged, API changes, etc. 
3. We'll review that PR together, merge it and then either @jcrugzz or I will publish. 

Once we've done that a few times happy to give you `npm publish` rights, but need to work up to that first. 

Let us know if you're still interested and thanks again for a really well written offer of help 🙏

**Comment by indexzero** [comment]
@jsmylnycky was able to set aside some time today to get Renovate installed and merge a number of documentation & example related PRs. 

We should be ready for a release if you'd like to give the PRs one look over for anything critical (but small in scope to be considered a patch).

Then if you can write-up the `CHANGELOG.md` for those PRs (if any) and `master` (see: https://github.com/http-party/node-http-proxy/commits/master) we should be ready to cut a release soon!

**Comment by benlavalley** [comment]
I see the really out of date websocket package was updated already which I spent a night trying to figure out in my own fork.  I do some really fun things with this package, so this is wonderful to see :)

**Comment by onigoetz** [comment]
Hi,

I'd be interested in giving some help in landing some PRs as well (Renovate updates, documentation improvements, some duplicate PRs)

I can't tell you that I can be a long term contributor, but I use this library for some work related projects and am starting to use it in another smaller project and would be interested to help triage some issues and get a release out.

**Comment by hcldan** [comment]
I was curious also about maintainers...  There's not much more I'd be able to do to help clean up stale deps...  
There are already a ton of open prs that are being handled by bots, but no one is merging them and the last commit on master is almost 2 years old now.

**Comment by emanuelecasadio** [comment]
Just checkin' in to see if this project is still maintained :)

@jcrugzz @jsmylnycky

**Comment by jsmylnycky** [comment]
> Just checkin' in to see if this project is still maintained :)
> 
> @jcrugzz @jsmylnycky

I dropped being a maintainer a couple years ago. I can't speak for the rest of the project or maintainers.

**Comment by emanuelecasadio** [comment]
PS: I forgot to tag also @indexzero
